const ALLOWED_LABELS = [
  // Core Food Categories & Descriptors
  "food",
  "dish",
  "meal",
  "cuisine",
  "ingredient",
  "produce",
  "vegetable",
  "fruit",
  "bread",
  "cheese",
  "pasta",
  "dessert",
  "salad",
  "recipe",
  "culinary arts",
  "garnish",
  "beverage",
  "drink",
  "snack",
  "supper",
  "breakfast",
  "lunch",
  "dinner",
  "stew",
  "soup",
  "roast",
  "grill",
  "bake",
  "fried",
  "sauté",
  "boiled",
  "raw",
  "organic",
  "fresh",
  "savory",
  "sweet",
  "spicy",
  "hot",
  "cold",

  // Tableware & Serving Items
  "tableware",
  "dishware",
  "plate",
  "bowl",
  "cup",
  "glass",
  "cutlery",
  "flatware",
  "serving dish",
  "tray",
  "saucer",
  "serving bowl",
  "mug",
  "goblet",
  "champagne flute",
  "wine glass",
  "chafing dish",
  "platter",
  "carving board",
  "serving plate",

  // Utensils
  "fork",
  "spoon",
  "knife",
  "chopsticks",
  "ladle",
  "tongs",
  "whisk",
  "spatula",
  "strainer",
  "grater",
  "peeler",
  "corkscrew",
  "nutcracker",
  "can opener",
  "skewer",
  "turner",
  "baster",
  "measuring cup",
  "measuring spoon",

  // Table Setting & Accessories
  "napkin",
  "napkin ring",
  "tablecloth",
  "placemat",
  "table setting",
  "dining table",
  "serving tray",
  "silverware",
  "coaster",
  "centerpiece",
  "table runner",
  "dinnerware",
  "cupboard",
  "bar set",

  // Candles & Ambiance
  "candle",
  "tealight",
  "candelabra",
  "votive",
  "scented candle",
  "pillar candle",

  // Containers & Holders
  "jar",
  "bottle",
  "carafe",
  "pitcher",
  "jug",
  "decanter",
  "bread basket",
  "fruit bowl",
  "container",
  "storage container",
  "pot",
  "pan",
  "saucepan",
  "kettle",
  "thermos",

  // Food Presentation & Garnishing
  "garnish",
  "sauce",
  "drizzle",
  "seasoning",
  "sprinkles",
  "glaze",
  "pastry",
  "presentation",
  "plating",
  "arrangement",
  "decoration",
  "finishing",
  "embellishment",

  // Drinks (non-alcoholic & alcoholic)
  "coffee",
  "tea",
  "espresso",
  "latte",
  "cappuccino",
  "matcha",
  "juice",
  "smoothie",
  "cocktail",
  "wine",
  "beer",
  "soda",
  "sparkling water",
  "mocktail",
  "lemonade",
  "infusion",
  "hot chocolate",

  // Special Food Types
  "charcuterie",
  "appetizer",
  "entree",
  "side dish",
  "gourmet",
  "homemade",
  "artisan",
  "confectionery",
  "finger food",
  "canapé",
  "tapas",
  "savoury",

  // International Cuisine Keywords
  "sushi",
  "tapas",
  "dim sum",
  "tortilla",
  "curry",
  "noodles",
  "dumpling",
  "baguette",
  "croissant",
  "fondue",
  "paella",
  "barbecue",
  "tandoori",
  "pho",
  "ramen",
  "bento",
  "shawarma",
  "falafel",
  "gyoza",
  "pierogi",
  "ceviche",
  "empanada",
  "mole",
  "kimchi",

  // Miscellaneous Safe Labels & Dining Experience
  "cooking",
  "kitchen",
  "serving",
  "buffet",
  "brunch",
  "dining",
  "feast",
  "banquet",
  "spread",
  "picnic",
  "smorgasbord",
  "supper club",
  "potluck",
  "reception",
  "table",

  // Descriptive & Contextual Terms (for top-down photography)
  "top view",
  "aerial view",
  "overhead",
  "bird's eye view",
  "flat lay",
  "minimal",
  "stylized",
  "artistic",
  "layout",
  "beef",
  "pork",
  "chicken",
  "turkey",
  "lamb",
  "veal",
  "ham",
  "sausage",
  "bacon",
  "salmon",
  "tuna",
  "shrimp",
  "lobster",
  "crab",
  "oyster",
  "scallop",
  "fish",
  "seafood",
  "sashimi",
  "tempura",
  "ravioli",
  "gnocchi",
  "lasagna",
  "stew",
  "chili",
  "roast",
  "barbecue",
  "smoked",
  "grilled",
  "marinated",
  "stir-fry",
  "rice",
  "quinoa",
  "couscous",
  "polenta",
  "pudding",
  "tart",
  "pie",
  "cookie",
  "brownie",
  "muffin",
  "cupcake",
  "ice cream",
  "gelato",
  "yogurt",
  "cheesecake",
  "donut",
  "bagel",
  "sandwich",
  "burger",
  "wrap",
  "taco",
  "burrito",
  "quesadilla",
  "nachos",
  "casserole",
  "omelette",
  "frittata",
  "scrambled",
  "poached",
  "boiled",
  "steamed",
  "baked",
  "crispy",
  "toasted",
  "smothered",
  "drizzled",
  "sautéed",
  "caramelized",
  "glazed",
  "stuffed",
  "filled",
  "layered",
  "rolled",
  "decorated",
  "plated",
  "arranged",
  "presented",
  "served",
  "culinary masterpiece",
  "gourmet creation",
  "chef's special",
  "artisan creation",
  "handcrafted",
  "exquisite",
  "elegant",
  "plated art",
  "food art",
  "food photography",
  "food styling",
  "top-down view",
  "overhead shot",
  "flat lay",
  "food arrangement",
  "symmetrical",
  "minimalist",
  "vibrant",
  "colorful",
  "fusion",
  "organic",
  "locally sourced",
  "farm-to-table",
  "sustainable",
  "freshly made",
  "homestyle",
  "comfort food",
  "classic",
  "traditional",
  "modern",
  "innovative",
  "deconstructed",
  "reimagined",
  "seasonal",
  "festive",
  "celebratory",
  "food festival",
  "plated perfection",
  "delicious",
  "mouthwatering",
  "appetizing",
  "tantalizing",
  "irresistible",
  "savory",
  "scrumptious",
  "yummy",
  "flavorful",
  "zesty",
  "spiced",
  "herbed",
  "seasoned",
  "simmered",
  "roasted",
  "slow-cooked",
  "infused",
  "browned",
  "seared",
  "charred",
  "smoked",
  "steeped",
  "marinated",
  "cured",
  "aged",
  "fermented",
  "pickled",
  "preserved",
  "crafted",
  "signature dish",
  "chef's selection",
  "award-winning",
  "celebrity chef",
  "foodie",
  "gastro",
  "epicurean",
  "fine dining",
  "casual dining",
  "rustic",
  "home-cooked",
  "bouillabaisse",
  "consommé",
  "bisque",
  "potage",
  "gumbo",
  "jambalaya",
  "ragu",
  "broth",
  "stock",
  "sauce",
  "dressing",
  "vinaigrette",
  "reduction",
  "emulsion",
  "aioli",
  "pesto",
  "chutney",
  "marmalade",
  "jam",
  "spread",
  "flambé",
  "sous-vide",
  "handcrafted pastry",
  "roasted garlic",
  "fresh basil",
  "herb-infused",
  "seasonal produce",
  "slow braised",
  "seared to perfection",
  "butter-poached",
  "flaky",
  "crispy",
  "light and airy",
  "rich and creamy",
  "silky",
  "velvety",
  "luxurious",
  "mouthwatering indulgence",
  "culinary delight",
  "food lover",
  "bistro style",
  "café style",
  "tapas style",
  "edible art",
  "culinary canvas",
  "food mosaic",
  "gastro art",
  "artisan baked",
  "hand-rolled",
  "crafted cocktails",
  "exotic flavors",
  "indulgent",
  "zesty lime",
  "crispy crust",
  "golden brown",
  "buttery",
  "nutty",
  "toasted sesame",
  "fresh cut",
  "hand-cut",
  "shaved",
  "decorative plating",
  "culinary innovation",
  "signature recipe",
  "chef inspired",
  "modern twist",
  "vintage flavors",
  "nostalgic",
  "comfort food classic",
  "family style",
  "shareable",
  "plated perfection",
  "culinary ritual",
  "culinary innovation",
  "signature recipe",
  "chef inspired",
  "modern twist",
  "vintage flavors",
  "nostalgic",
  "comfort food classic",
  "family style",
  "shareable",
  "plated perfection",
  "culinary ritual",
  "savory blend",
  "sweet medley",
  "fiery",
  "smoky",
  "sizzling",
  "zesty burst",
  "spoon-worthy",
  "fork-worthy",
  "baked to perfection",
  "oven-fresh",
  "delicately spiced",
  "roasted to perfection",
  "artisan crafted",
  "curated flavors",
  "taste sensation",
  "exquisite presentation",
  "delectable",
  "ambrosial",
  "divine",
  "taste explosion",
  "symphony of flavors",
  "flavor harmony",
  "culinary showcase",
  "table centerpiece",
  "festive spread",
  "holiday special",
  "seasonal special",
  "farm fresh",
  "sun-ripened",
  "earth to table",
  "homestyle cooking",
  "traditional recipe",
  "modern cuisine",
  "food artistry",
  "epicurean journey",
  "gastronomic experience",
  "taste adventure",
  "culinary journey",
  "innovative fusion",
  "freshly prepared",
  "chef's masterpiece",
  "signature creation",
  "gourmet indulgence",
  "refined taste",
  "luxurious plating",
  "hand-selected ingredients",
  "quality ingredients",
  "seasonally inspired",
  "local flavors",
  "world flavors",
  "exotic spices",
  "global cuisine",
  "cultural feast",
  "ethnic flavors",
  "vibrant presentation",
  "visual feast",
  "plated beauty",
  "artful presentation",
  "chef-curated",
  "chef's creation",
  "taste perfection",
  "perfectly balanced",
  "flavor profile",
  "culinary finesse",
  "culinary craft",
  "epicurean art",
  "chocolate",
  "cocoa",
  "almond",
  "pistachio",
  "hazelnut",
  "cashew",
  "walnut",
  "peanut",
  "crouton",
  "ginger",
  "garlic",
  "onion",
  "scallion",
  "spring onion",
  "parsley",
  "cilantro",
  "basil",
  "oregano",
  "rosemary",
  "thyme",
  "sage",
  "mint",
  "arugula",
  "spinach",
  "kale",
  "quinoa salad",
  "roasted vegetables",
  "curry dish",
  "masala",
  "spaghetti",
  "fettuccine",
  "penne",
  "lasagna noodles",
  "eggplant",
  "zucchini",
  "squash",
  "mushroom",
  "portobello",
  "truffle",
  "truffle oil",
  "umami",
  "fermented soy",
  "tofu",
  "edamame",
  "rice noodles",
  "fried rice",
  "sushi rice",
  "miso",
  "kimchi",
  "biryani",
  "pilaf",
  "risotto",
  "cheddar",
  "mozzarella",
  "feta",
  "brie",
  "camembert",
  "parmesan",
  "ricotta",
  "buttermilk",
  "yolk",
  "egg white",
  "omelette",
  "scrambled eggs",
  "soft-boiled eggs",
  "poached eggs",
  "bacon bits",
  "sausage links",
  "ham slice",
  "meatball",
  "gravy",
  "stew pot",
  "wok",
  "skillet",
  "frying pan",
  "cast iron",
  "casserole dish",
  "raw food",
  "fresh produce",
  "farm produce",
  "organic vegetables",
  "gluten-free",
  "vegan",
  "vegetarian",
  "non-dairy",
  "lactose-free",
  "sugar-free",
  "low-carb",
  "whole grain",
  "superfood",
  "energy bowl",
  "power bowl",
  "acai bowl",
  "poke bowl",
  "granola",
  "oatmeal",
  "cereal",
  "muesli",
  "smoothie bowl",
  "breakfast bowl",
  "brunch plate",
  "dinner plate",
  "lunch box",
  "food truck",
  "street food",
  "buffet table",
  "tasting menu",
  "degustation",
  "plated meal",
  "food presentation",
  "garnished",
  "artfully arranged",
  "colorful plating",
  "sauce drizzle",
  "edible garnish",
  "edible flowers",
  "microgreens",
  "sprouts",
  "herb garnish",
  "seasonal garnish",
  "topping",
  "parmesan topping",
  "chocolate drizzle",
  "cocoa powder",
  "icing",
  "frosting",
  "sprinkled",
  "dusted",
  "finely chopped",
  "diced",
  "julienned",
  "sliced",
  "shredded",
  "grated",
  "crumbled",
  "toasted",
  "baked",
  "boiled",
  "steamed",
  "blanched",
  "poached",
  "simmered",
  "braised",
  "stewed",
  "stirred",
  "mixed",
  "layered",
  "stacked",
  "molded",
  "shaped",
  "artisanal",
  "handmade",
  "crafted",
  "cooked to order",
  "chef-prepared",
  "umami",
  "fusion cuisine",
  "molecular gastronomy",
  "food display",
  "culinary display",
  "arranged meal",
  "finger food",
  "bite-sized",
  "garnished",
  "sliced",
  "diced",
  "chopped",
  "minced",
  "smoked salmon",
  "truffle",
  "truffle oil",
  "saffron",
  "aromatic",
  "zest",
  "lemon zest",
  "lime zest",
  "pomegranate",
  "avocado",
  "organic produce",
  "farm fresh ingredients",
  "handcrafted",
  "chef's plate",
  "plated dish",
  "artfully arranged",
  "exotic delicacy",
  "gourmandise",
  "hearty",
  "succulent",
  "juicy",
  "tender",
  "fluffy",
  "rich",
  "creamy",
  "velvety",
  "silky sauce",
  "drizzled sauce",
  "balsamic reduction",
  "herbaceous",
  "roasted to perfection",
  "oven-roasted",
  "slow roasted",
  "smoke-infused",
  "seared perfection",
  "charred edges",
  "crisply fried",
  "lightly battered",
  "steamed gently",
  "poached delicately",
  "braised",
  "glazed finish",
  "finely plated",
  "elegantly presented",
  "culinary elegance",
  "artistic plating",
  "visual feast",
  "edible art",
  "taste explosion",
  "flavor fusion",
  "seasoned to perfection",
  "hand-selected ingredients",
  "gourmet ingredients",
  "premium cut",
  "signature blend",
  "infused oil",
  "seasonal harvest",
  "fresh-picked",
  "locally sourced",
  "market-fresh",
  "heirloom",
  "artisan crafted",
  "rustic charm",
  "modern presentation",
  "minimalist plating",
  "overhead composition",
  "bird's-eye layout",
  "flat lay style",
  "top-down aesthetic",
  "symmetrical layout",
  "balanced composition",
  "mostaccioli",
  "french fries",
  "meat",
  "serveware",
  "waffle",
  "belgian waffle",
  "barware",
  "cake",
  "condiment",
];

module.exports = ALLOWED_LABELS;
